src/Entity/Announces.php
<?php

namespace App\Entity;

use App\Entity\Users;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\AnnouncesRepository;

/**
 * @ORM\Entity(repositoryClass=AnnouncesRepository::class)
 */
class Announces
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Address;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $City;

    /**
     * @ORM\Column(type="integer")
     */
    private $postcode;

    /**
     * @ORM\Column(type="float")
     */
    private $daily_price;

    /**
     * @ORM\Column(type="string", length=500, nullable=true)
     */
    private $images;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="announces")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user_ID;

    /**
     * @ORM\OneToMany(targetEntity=Reservations::class, mappedBy="announce_id")
     */
    private $reservations;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     */
    private $max_animals;


    public function __construct()
    {
        $this->reservations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAddress(): ?string
    {
        return $this->Address;
    }

    public function setAddress(string $Address): self
    {
        $this->Address = $Address;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->City;
    }

    public function setCity(string $City): self
    {
        $this->City = $City;

        return $this;
    }

    public function getPostcode(): ?int
    {
        return $this->postcode;
    }

    public function setPostcode(int $postcode): self
    {
        $this->postcode = $postcode;

        return $this;
    }

    public function getDailyPrice(): ?float
    {
        return $this->daily_price;
    }

    public function setDailyPrice(float $daily_price): self
    {
        $this->daily_price = $daily_price;

        return $this;
    }

    public function getImages(): ?string
    {
        return $this->images;
    }

    public function setImages(?string $images): self
    {
        $this->images = $images;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getUserID(): ?User
    {
        return $this->user_ID;
    }

    public function setUserID(?User $user_ID): self
    {
        $this->user_ID = $user_ID;

        return $this;
    }

    /**
     * @return Collection|Reservations[]
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservations $reservation): self
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations[] = $reservation;
            $reservation->setAnnounceId($this);
        }

        return $this;
    }

    public function removeReservation(Reservations $reservation): self
    {
        if ($this->reservations->removeElement($reservation)) {
            // set the owning side to null (unless already changed)
            if ($reservation->getAnnounceId() === $this) {
                $reservation->setAnnounceId(null);
            }
        }

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getMaxAnimals(): ?int
    {
        return $this->max_animals;
    }

    public function setMaxAnimals(int $max_animals): self
    {
        $this->max_animals = $max_animals;

        return $this;
    }

}

src/Form/AnnouncesType.php
<?php

namespace App\Form;

use App\Entity\Announces;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class AnnouncesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextType::class, [
                'label' => 'Titre de votre annonce',
                'attr'=> [
                    'placeholder' => "Couple de retraité habitant à côté d'une grande forêt",
                ],
            ])
            ->add('description', TextType::class, [
                'label' => "Décrivez vous, votre logement, les alentours, vos habitudes avec les chiens...",
                'attr'=> [
                    'placeholder' => "Ex : Maison avec jardin. Nous réalisons 3 promenades par jour, dans la fôret ou autour du lac...",
                ],
            ])
            ->add('address', TextType::class, [
                'label' => "Adresse",
                'attr'=> [
                    'placeholder' => "Votre adresse",
                ],
            ])
            ->add('city', TextType::class, [
                'label' => "Ville",
                'attr'=> [
                    'placeholder' => "Votre ville",
                ],
            ])
            ->add('postcode', NumberType::class, [
                'label' => "Code Postal",
                'attr'=> [
                    'placeholder' => "Votre code postal",
                ],
                ])
            ->add('daily_price', NumberType::class, [
                'label' => "Prix journalier (en €)",
                'attr'=> [
                    'placeholder' => "€/jour",
                ],
            ])
            ->add('max_animals', ChoiceType::class, [
                'label' => "Combien d'animaux pouvez-vous accueillir chez vous?",
                'choices'  => [
                    '1' => 1,
                    '2' => 2,
                    '3' => 3,
                    '4' => 4,
                ],
            ])
            ->add('images', FileType::class, [
                'mapped' => false,
                'required' => false,
                'multiple' => false,
                'label' => "Uploader une image.",
                'attr'=> [
                    'placeholder' => "Parcourir les fichiers.",
                ],
                'constraints' => [
                    new File([
                        'maxSize' => "2048K",
                        'mimeTypes' => [
                            'image/png',
                            'image/jpg',
                            'image/jpeg',
                            'image/gif',
                        ],
                    ])
                ],
            ])
            ->add('envoyer', SubmitType::class, [
                'label' => "Déposer votre annonce",
                "attr" => [
                    "class" => "btn secondary"
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Announces::class,
        ]);
    }
}

src/Controller/AnnouncesController.php
<?php

namespace App\Controller;

use App\Entity\Announces;
use App\Form\AnnouncesType;
use Doctrine\ORM\Mapping\Id;
use App\Service\UploadService;
use App\Service\CheckReservation;
use App\Repository\UserRepository;
use App\Service\CheckReservations;
use Doctrine\DBAL\Types\StringType;
use App\Repository\AnnouncesRepository;
use App\Repository\ReservationsRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Security;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/announces')]
class AnnouncesController extends AbstractController
{
    /**
     * @var Security
     */
    private $security;

    public function __construct(Security $security)
    {
       $this->security = $security;
    }

    #[Route('/', name: 'announces_index', methods: ['GET'])]
    public function index(AnnouncesRepository $announcesRepository): Response
    {
        
        return $this->render('announces/index.html.twig', [
            'announces' => $announcesRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'announces_new', methods: ['GET','POST'])]
    public function new(Request $request, UploadService $uploader): Response
    {
        $announce = new Announces();
        $form = $this->createForm(AnnouncesType::class, $announce);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $imageFile = $form->get('images')->getData();
            if($imageFile)
            {
                $fileName = $uploader->upload($imageFile);

                $announce->setImages($fileName);
            }

            $user = $this->getUser();
            $announce->setUserID($user);

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($announce);
            $entityManager->flush();

            return $this->redirectToRoute('announces_show', [
                'id' => $announce->getId(),
            ], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('announces/new.html.twig', [
            'announce' => $announce,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', defaults: ['start', 'end'], name: 'announces_show', methods: ['GET','POST'])]
    public function show(Announces $announce, Request $request, UserRepository $userRepository, CheckReservations $checker, ReservationsRepository $reservationsRepository): Response
    {
        $activeUser = $this->security->getUser();
        $city = $request->attributes->get('announce')->getCity();
        $referer = $request->headers->get('referer');

        $reservations = $checker->check($announce->getId(), $reservationsRepository);
        $resa = [];
        foreach( $reservations as $reservation)
        {
            $resa[] = [

                'id' => $reservation->getId(),
                'start' => $reservation->getStart()->format('Y-m-d H:i:s'),
                'end' => $reservation->getEnd()->format('Y-m-d H:i:s'),
                'title' => 'Contrat',
            ];
        }

        $data =json_encode($resa);

        
        $user = $userRepository->findUserByID($announce->getUserID())[0];
        // dd($announce->getUserID());

        if($activeUser == $user)
        {
            return $this->render('announces/show.html.twig', [
                'announce' => $announce,
                'previousPage' => $referer,
                'user' => $user,
                'activeUser' => $activeUser,
                'previousCity' => $city,
                'data' => $data
            ]);
        }
        else
        {
            
            $form = $this->createFormBuilder(null)
            ->setAction($this->generateUrl('reservation_book', array(
                'id' => $announce->getId(),
                'user' => $user,
                )))
            ->add('start', DateType::class, array(
                'label' => "Du  ",
                'required' => true,
                'widget' => 'single_text',
                'html5' => false,
                'attr' => [
                    'autocomplete' => "off",
                    'placeholder' => "Arrivée",
                    'class' => 'js-datepicker inputStart',
                    'id' => 'start',
                    'data-provide' => 'datetimepicker',
                ],
                ))
            ->add('end', DateType::class, array(
                'label' => "Au  ",
                'required' => true,
                'widget' => 'single_text',
                'html5' => false,
                'attr' => [
                    'autocomplete' => "off",
                    'placeholder' => "Départ",
                    'class' => 'js-datepicker inputEnd',
                    'id' => 'end',
                    'data-provide' => 'datetimepicker',
                ],
                ))
            ->add('book', SubmitType::class, [
                'label' => "Réserver",
                'attr' => [
                    'class' => 'btn mt-3 primary'
                ],
            ])
            ->getForm();

            return $this->render('announces/show.html.twig', [
                'announce' => $announce,
                'previousPage' => $referer,
                'user' => $user,
                'activeUser' => $activeUser,
                'previousCity' => $city,
                'form' => $form->createView(),
                'data' => $data
            ]);
        }
    }

    #[Route('/{id}/edit', name: 'announces_edit', methods: ['GET','POST'])]
    public function edit(Request $request, Announces $announce, UploadService $uploader): Response
    {
        $form = $this->createForm(AnnouncesType::class, $announce);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $imageFile = $form->get('images')->getData();
            if($imageFile == null)
            {
                $announce->setImages($announce->getImages());
            }
            else
            {
                $fileName = $uploader->upload($imageFile);

                $announce->setImages($fileName);
            }
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('announces_show', [
                'id' => $announce->getId(),
            ], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('announces/edit.html.twig', [
            'announce' => $announce,
            'form' => $form,
        ]);
    }

    #[Route('/{id}/delete', name: 'announces_delete', methods: ['GET','POST'])]
    public function delete(Request $request, Announces $announce): Response
    {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($announce);
            $entityManager->flush();

        return $this->redirectToRoute('home_index', [], Response::HTTP_SEE_OTHER);
    }

}

templates/announces/_delete_form.html.twig
<form method="post" action="{{ path('announces_delete', {'id': announce.id}) }}" onsubmit="return confirm('Voullez-vous vraiment supprimer votre annonce?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ announce.id) }}">
    <button class="btn btn-danger mb-5">Supprimmer l'annonce</button>
</form>

templates/announces/_form.html.twig
{{ form_start(form) }}


{{ form_label(form.title) }}
{{ form_errors(form.title) }}
{{ form_widget(form.title) }}

<div class="mt-2">
    {{ form_label(form.description) }}
    {{ form_errors(form.description) }}
    {{ form_widget(form.description) }}
</div>

<div class="mt-2">
    {{ form_label(form.max_animals) }}
    {{ form_errors(form.max_animals) }}
    {{ form_widget(form.max_animals) }}
</div>

<div class="row mt-2">
    <div class="col-4">
        {{ form_label(form.address) }}
        {{ form_errors(form.address) }}
        {{ form_widget(form.address) }}
    </div>
    <div class="col-4">
        {{ form_label(form.city) }}
        {{ form_errors(form.city) }}
        {{ form_widget(form.city) }}
    </div>
    <div class="col-4">
        {{ form_label(form.postcode) }}
        {{ form_errors(form.postcode) }}
        {{ form_widget(form.postcode) }}
    </div>
</div>

<div class="mt-2">
    {{ form_label(form.daily_price) }}
    {{ form_errors(form.daily_price) }}
    {{ form_widget(form.daily_price) }}
</div>

{% if form.vars.value.images != "" %}
<div>
    <p>Image actuelle</p>
    <img class="img-size-little" src="/image/upload/{{ form.vars.value.images }}" alt="image">
</div>
{% endif %}

<div class="mt-2">
    {{ form_label(form.images) }}
    {{ form_errors(form.images) }}
    {{ form_widget(form.images) }}
</div>

<div class="mb-2 mt-4">
    
    {{ form_label(form.envoyer) }}
    {# <a class="btn primary" href="{{ path('announces_index') }}">Retour</a> #}
</div>
{{ form_end(form) }}

templates/announces/displaySearch.html.twig
{% extends 'base.html.twig' %}

{% block title %}Résultat{% endblock %}

{% block body %}
    <h1 class="container">Résultat de votre recherche</h1>

{% if announces %}
<div class="announces_list">
    <ul class="gardiens">
    {# AFFICHER UNE CARTE POUR CHAQUE ANNONCE CORRESPONDANT AU FILTRE (VILLE) #}
    {% for announce in announces %}
                <li>
                    <a href="{{ path('announces_show', {'id': announce.id}) }}">
                        <div class="card">
                        {% if announce.images == null %}
                            <img src="/image/no_photo.png" class="card-img-top" alt="Photo de l'annonce. C'est une plaine avec un texte par dessus. Cela signifie que l'utilisateur n'a pas rensigné de photo dans son annonce.">
                        {% else %}
                            <img src="/image/upload/{{ announce.images }}" class="card-img-top" alt="Photo de l'annonce. Elle représente le domicile d'un gardien.">
                        {% endif %}
                            <div class="card-body">
                                <h3 class="card-title">{{ announce.title }}</h3>
                                {% for address in addressCoordinates %}
                                    {% if address.id == announce.id %}                                
                                        <p class="card-text item js-marker" 
                                        data-lat={{ address.latitude }} data-lng={{ address.longitude }} data-price={{ announce.DailyPrice }}>
                                        {{ announce.Address }}, {{ announce.postcode }}, {{ announce.City }}</p>
                                        <p>Prix journalier : {{ announce.DailyPrice }} €</p>
                                    {% endif %}
                                {% endfor %}
                                <button href="{{ path('announces_show', {'id': announce.id, 'start': start, 'end': end}) }}" class="btn btn-primary">Consulter l'annonce</button>
                            </div>
                        </div>
                    </a>
                </li>
    {% endfor %}
    </ul>
    <div class="map" id="map"></div>
</div>
{# GERER LE CAS OU IL N'Y A PAS D'ANNONCES DANS LA VILLE RECHERCHEE
    ET LUI OFFRIR UNE SOILUTION POUR SE REDIRIGER A L'INDEX          #}
{% else %}
<div class="container" id="search_failed">
    <p>Aucune annonce ne correspond à la ville que vous recherchez</p>
    <a href="{{ path("home_index") }}" class="btn primary mb-3">Retour à la page d'accueil</a>
</div>
{% endif %}
{% endblock %}

templates/announces/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Announces{% endblock %}

{% block body %}
    <h1>Editer votre annonce</h1>

    <div id="edit">
        {{ include('announces/_form.html.twig', {'button_label': 'Update'}) }}
    </div>

    {{ include('announces/_delete_form.html.twig') }}
{% endblock %}

{% block javascripts %}
<script src="/js/editButton.js"></script>
{% endblock %}

templates/announces/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Announces index{% endblock %}

{% block body %}

    <h1>Announces index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Titre</th>
                <th>Adresse</th>
                <th>Ville</th>
                <th>Code postal</th>
                <th>Prix journalier</th>
                <th>Propriétaire</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for announce in announces %}
            <tr>
                <td>{{ announce.id }}</td>
                <td>{{ announce.title }}</td>
                <td>{{ announce.Address }}</td>
                <td>{{ announce.City }}</td>
                <td>{{ announce.postcode }}</td>
                <td>{{ announce.dailyPrice }}</td>
                <td>{{ announce.userID.firstname }} {{ announce.userID.lastname }}</td>
                <td>
                    <a class="btn primary" href="{{ path('announces_show', {'id': announce.id}) }}">Consulter</a>
                    <a class="btn secondary" href="{{ path('announces_edit', {'id': announce.id}) }}">Modifier</a>
                    <a class="btn btn-danger" href="{{ path('announces_delete', {'id': announce.id}) }}" onclick="return confirm('Voullez-vous vraiment supprimer votre annonce?');">Supprimer</a>
                    <a class="btn btn-warning" href="{{ path('messages_send', {'id': announce.userID}) }}">Contacter</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/announces/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvelle Announce{% endblock %}

{% block body %}
<div class="container" id="new_announce">
    <div class="col-8" id="form_announce">
        <h1 class="mt-2 mb-4">Déposer une annonce</h1>
        
        {{ include('announces/_form.html.twig') }}
    </div>
    <div class="col-4">
        <img class="img_register" src="../image/Maison.jpg" alt="">
    </div>
</div>
{% endblock %}